// User reducer types
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_ERROR = 'USER_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CURRENT_USER = 'CURRENT_USER';
export const NO_CURRENT_USER = 'NO_CURRENT_USER';

// Group reducer types
export const FETCH_GROUPS_REQUEST = 'FETCH_GROUPS_REQUEST';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_ERROR = 'FETCH_GROUPS_ERROR';
export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';
export const FETCH_GROUP_REQUEST = 'FETCH_GROUP_REQUEST';
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS';
export const FETCH_GROUP_ERROR = 'FETCH_GROUP_ERROR';
export const JOIN_GROUP_REQUEST = 'JOIN_GROUP_REQUEST';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
export const JOIN_GROUP_ERROR = 'JOIN_GROUP_ERROR';
export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR';
export const LEAVE_GROUP_REQUEST = 'LEAVE_GROUP_REQUEST';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_ERROR = 'LEAVE_GROUP_ERROR';

// Expense reducer types
export const EXPENSE_REQUEST = 'EXPENSE_REQUEST';
export const EXPENSE_SUCCESS = 'EXPENSE_SUCCESS';
export const EXPENSE_ERROR = 'EXPENSE_ERROR';
export const EXPENSE_RESET = 'EXPENSE_RESET';
export const EXPENSE_DELETED = 'EXPENSE_DELETED';
export const USERS_TOTAL_REQUEST = 'USERS_TOTAL_REQUEST';
export const USERS_TOTAL_SUCCESS = 'USERS_TOTAL_SUCCESS';
export const USERS_TOTAL_ERROR = 'USERS_TOTAL_ERROR';
export const USER_TOTAL_REQUEST = 'USER_TOTAL_REQUEST';
export const USER_TOTAL_SUCCESS = 'USER_TOTAL_SUCCESS';
export const USER_TOTAL_ERROR = 'USER_TOTAL_ERROR';
export const CREATED_EXPENSE_REQUEST = 'CREATED_EXPENSE_REQUEST';
export const CREATED_EXPENSE_SUCCESS = 'CREATED_EXPENSE_SUCCESS';
export const CREATED_EXPENSE_ERROR = 'CREATED_EXPENSE_ERROR';
