// User reducer types
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_REQUEST = "USER_REQUEST";
export const USER_ERROR = "USER_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
export const CURRENT_USER = "CURRENT_USER";
export const NO_CURRENT_USER = "NO_CURRENT_USER";

// Group reducer types
export const JOINED_GROUPS_REQUEST = "JOINED_GROUPS_REQUEST";
export const JOINED_GROUPS_SUCCESS = "JOINED_GROUPS_SUCCESS";
export const JOINED_GROUPS_ERROR = "JOINED_GROUPS_ERROR";
export const CREATED_GROUPS_REQUEST = "CREATED_GROUPS_REQUEST";
export const CREATED_GROUPS_SUCCESS = "CREATED_GROUPS_SUCCESS";
export const CREATED_GROUPS_ERROR = "CREATED_GROUPS_ERROR";
export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_ERROR = "CREATE_GROUP_ERROR";
